[project]
name = "parsing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ace-tools>=0.0",
    "argparse>=1.4.0",
    "pandas>=2.2.3",
    "prettytable>=3.11.0",
    "rich>=13.9.3",
]
