name: Release

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'


permissions:
  contents: write  # Allows the bot to push changes

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v6.0.0
        with:
          github-token: ${{ secrets.CHANGELOG_RELEASE }}
          # Optional: specify additional options here 
      
      # create release
      - name: Create Release
        uses: actions/create-release@v1
        with:
          github-token: ${{ secrets.CHANGELOG_RELEASE }}
          tag_name: ${{ github.event.release.tag_name }}
          release_name: ${{ github.event.release.name }}
          draft: false
          prerelease: false

