name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers when semantic version tags are pushed

permissions:
  contents: write  # Required for GitHub to push changes and create releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Corrected token usage
        with:
          preset: angular  # Optional: use 'angular' for the changelog style
          outputFile: CHANGELOG.md  # Generates a changelog file
          versionFile: ./package.json  # Optional: bumps the version in package.json
          versionPath: version  # Optional: updates the version field in package.json

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # Uses the pushed tag as the release tag
          release_name: Release ${{ github.ref_name }}  # Automatically names the release based on the tag
          body_path: CHANGELOG.md  # Uses the CHANGELOG.md as the release notes
          draft: false  # Not a draft release
          prerelease: false  # Not a prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Corrected token usage
          #
