name: Release

on:
  push:
    branches:
      - main  # Automatically trigger on push to the 'main' branch

permissions:
  contents: write  # Required for GitHub to push changes, create tags, and release versions

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Generate Changelog and Determine New Version
      - name: Generate Changelog and Bump Version
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          preset: angular
          output-file: CHANGELOG.md
          version-file: pyproject.toml
          version-path: tool.poetry.version
          skip-on-empty: true
          tag-prefix: 'v'

      # Step 3: Create a new GitHub release
      - name: Create Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}  # Only run if not skipped
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}  # Use the tag output directly
          release_name: Release ${{ steps.changelog.outputs.tag }}  # Use the tag output for release name
          body: ${{ steps.changelog.outputs.clean_changelog }}  # Use clean_changelog for release notes
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
